changelog:
  categories:
    - title: "What's Changed"
      labels:
        - "*"
      exclude:
        labels:
          - "renovate"
    - title: "Dependencies"
      labels:
        - "renovate"
        - "dependencies"
