changelog:
  categories:
    - title: "Improvements"
      labels:
        - "*"
      exclude:
        labels:
          - "dependencies"
    - title: "Dependencies"
      labels:
        - "dependencies"
    - title: "CI/CD"
      labels:
        - "cicd"
